//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalysisResult
    {
        public AnalysisResult()
        {
            this.AnalysisResultStatus = new HashSet<AnalysisResultStatu>();
        }
    
        public int AnalysisResultID { get; set; }
        public int RquestedAnalysisID { get; set; }
        public string Result { get; set; }
        public int ExamineByEmployeeID { get; set; }
        public System.DateTime ExamineDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<AnalysisResultStatu> AnalysisResultStatus { get; set; }
    }
}
