//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceAnalysis = new HashSet<DeviceAnalysi>();
        }
    
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceDescription { get; set; }
        public int UnitId { get; set; }
        public bool IsDefalutUnitDevice { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual ICollection<DeviceAnalysi> DeviceAnalysis { get; set; }
    }
}
