//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DeviceAnalysis = new HashSet<DeviceAnalysi>();
            this.DevicePlans = new HashSet<DevicePlan>();
            this.NotDeliveredAnalysis = new HashSet<NotDeliveredAnalysi>();
            this.Organizations = new HashSet<Organization>();
            this.Patients = new HashSet<Patient>();
            this.PatientRequests = new HashSet<PatientRequest>();
            this.PatientRequestAnalysis = new HashSet<PatientRequestAnalysi>();
            this.PatientRequestAnalysisStatus = new HashSet<PatientRequestAnalysisStatu>();
            this.PatientRequestPayments = new HashSet<PatientRequestPayment>();
            this.PatientRequestStatus = new HashSet<PatientRequestStatu>();
            this.RejectedAnalysis = new HashSet<RejectedAnalysi>();
            this.RequestedAnalysisResults = new HashSet<RequestedAnalysisResult>();
            this.Users = new HashSet<User>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime JobDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Phone { get; set; }
        public int CurrentBranchID { get; set; }
        public int JobTitleID { get; set; }
    
        public virtual ICollection<DeviceAnalysi> DeviceAnalysis { get; set; }
        public virtual ICollection<DevicePlan> DevicePlans { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual LabBranch LabBranch { get; set; }
        public virtual ICollection<NotDeliveredAnalysi> NotDeliveredAnalysis { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<PatientRequest> PatientRequests { get; set; }
        public virtual ICollection<PatientRequestAnalysi> PatientRequestAnalysis { get; set; }
        public virtual ICollection<PatientRequestAnalysisStatu> PatientRequestAnalysisStatus { get; set; }
        public virtual ICollection<PatientRequestPayment> PatientRequestPayments { get; set; }
        public virtual ICollection<PatientRequestStatu> PatientRequestStatus { get; set; }
        public virtual ICollection<RejectedAnalysi> RejectedAnalysis { get; set; }
        public virtual ICollection<RequestedAnalysisResult> RequestedAnalysisResults { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
