//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabBranch
    {
        public LabBranch()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public int CityID { get; set; }
        public string Phone { get; set; }
        public System.DateTime EstablishedDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
