//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotDeliveredAnalysi
    {
        public int NotDeliveredId { get; set; }
        public int RequestedAnalysisId { get; set; }
        public System.DateTime NotDeliveredDate { get; set; }
        public int ReasonId { get; set; }
    
        public virtual NotDeliveredReason NotDeliveredReason { get; set; }
        public virtual PatientRequestAnalysi PatientRequestAnalysi { get; set; }
    }
}
