//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationCondition
    {
        public int OrganizationConditionID { get; set; }
        public int OrganizationID { get; set; }
        public int ConditionID { get; set; }
        public Nullable<bool> IsFound { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
