//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationInfo
    {
        public int OrganizationInfoID { get; set; }
        public int OrganizationID { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Phone { get; set; }
    
        public virtual City City { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
