//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Organizations = new HashSet<Organization>();
            this.PackageCostLists = new HashSet<PackageCostList>();
        }
    
        public int PackageID { get; set; }
        public string PackageName { get; set; }
        public string PackageDiscription { get; set; }
        public int CategoryTypeID { get; set; }
    
        public virtual CategoryType CategoryType { get; set; }
        public virtual ICollection<Organization> Organizations { get; set; }
        public virtual ICollection<PackageCostList> PackageCostLists { get; set; }
    }
}
