//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRequest_Payment
    {
        public int PatientID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int PatientRequestEmployeeID { get; set; }
        public string RequestComment { get; set; }
        public Nullable<int> DoctorRefID { get; set; }
        public string Priority { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string RequestedRefID { get; set; }
        public string AttachmentSession { get; set; }
        public Nullable<decimal> ExtraDiscount { get; set; }
        public Nullable<decimal> ExtraCost { get; set; }
        public Nullable<decimal> TotalPatientCost { get; set; }
        public Nullable<decimal> TotalOrganizationCost { get; set; }
        public int PaymentID { get; set; }
        public int RequestID { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentEmployeeID { get; set; }
        public string PaymentComment { get; set; }
        public string RequestNumber { get; set; }
    }
}
