//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRequestAnalysi
    {
        public PatientRequestAnalysi()
        {
            this.DeviceAnalysis = new HashSet<DeviceAnalysi>();
            this.NotDeliveredAnalysis = new HashSet<NotDeliveredAnalysi>();
            this.PatientRequestAnalysisStatus = new HashSet<PatientRequestAnalysisStatu>();
            this.RejectedAnalysis = new HashSet<RejectedAnalysi>();
        }
    
        public int RequestedAnalysisID { get; set; }
        public int RequestID { get; set; }
        public int AnalysisID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int EmployeeID { get; set; }
        public string RunNumber { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual ICollection<DeviceAnalysi> DeviceAnalysis { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<NotDeliveredAnalysi> NotDeliveredAnalysis { get; set; }
        public virtual PatientRequest PatientRequest { get; set; }
        public virtual ICollection<PatientRequestAnalysisStatu> PatientRequestAnalysisStatus { get; set; }
        public virtual ICollection<RejectedAnalysi> RejectedAnalysis { get; set; }
    }
}
