//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int ProvinceID { get; set; }
        public int CountryID { get; set; }
        public string ProvinceName { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
