//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RejectionResson
    {
        public RejectionResson()
        {
            this.RejectedAnalysis = new HashSet<RejectedAnalysi>();
        }
    
        public int ErrorId { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual ICollection<RejectedAnalysi> RejectedAnalysis { get; set; }
        public virtual RejectionResson RejectionResson1 { get; set; }
        public virtual RejectionResson RejectionResson2 { get; set; }
    }
}
