//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestedAnalysisResult
    {
        public int RequestedAnalysisResultId { get; set; }
        public int RequestedAnalysisId { get; set; }
        public System.DateTime ResultDate { get; set; }
        public string ResultValue { get; set; }
        public int EmployeeId { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PatientRequestAnalysi PatientRequestAnalysi { get; set; }
    }
}
