//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleType
    {
        public SampleType()
        {
            this.Analyses = new HashSet<Analysis>();
        }
    
        public int SampleTypeID { get; set; }
        public string SampleType1 { get; set; }
    
        public virtual ICollection<Analysis> Analyses { get; set; }
    }
}
