//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitDevice
    {
        public int UnitId { get; set; }
        public int DeviceId { get; set; }
        public int SeparatedSampleId { get; set; }
        public bool IsDefaultDevice { get; set; }
    }
}
