//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit_Device_SeparatedSample
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string DeviceCode { get; set; }
        public string DeviceDescription { get; set; }
        public int Capacity { get; set; }
        public bool IsDefaultDevice { get; set; }
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
        public int SampleTypeID { get; set; }
        public string SampleType { get; set; }
        public string SeparatedSampleName { get; set; }
        public int SeparatedSampleId { get; set; }
    }
}
