//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Analyses = new HashSet<Analysis>();
            this.Devices = new HashSet<Device>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public string UnitDescription { get; set; }
    
        public virtual ICollection<Analysis> Analyses { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
