//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoMisrInternationalLab.Resources.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisCaptureResult.
        /// </summary>
        public static string AnalysisCaptureResult {
            get {
                return ResourceManager.GetString("AnalysisCaptureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisMovedToLab.
        /// </summary>
        public static string AnalysisMovedToLab {
            get {
                return ResourceManager.GetString("AnalysisMovedToLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisNotDelivered.
        /// </summary>
        public static string AnalysisNotDelivered {
            get {
                return ResourceManager.GetString("AnalysisNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisPendingForSampling.
        /// </summary>
        public static string AnalysisPendingForSampling {
            get {
                return ResourceManager.GetString("AnalysisPendingForSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisReceivedOnDevice.
        /// </summary>
        public static string AnalysisReceivedOnDevice {
            get {
                return ResourceManager.GetString("AnalysisReceivedOnDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisRejected.
        /// </summary>
        public static string AnalysisRejected {
            get {
                return ResourceManager.GetString("AnalysisRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisSampled.
        /// </summary>
        public static string AnalysisSampled {
            get {
                return ResourceManager.GetString("AnalysisSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisSaved.
        /// </summary>
        public static string AnalysisSaved {
            get {
                return ResourceManager.GetString("AnalysisSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisTransferred.
        /// </summary>
        public static string AnalysisTransferred {
            get {
                return ResourceManager.GetString("AnalysisTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisUnderTesting.
        /// </summary>
        public static string AnalysisUnderTesting {
            get {
                return ResourceManager.GetString("AnalysisUnderTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalysisWaitingForReportApproved.
        /// </summary>
        public static string AnalysisWaitingForReportApproved {
            get {
                return ResourceManager.GetString("AnalysisWaitingForReportApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientRequestPending.
        /// </summary>
        public static string PatientRequestPending {
            get {
                return ResourceManager.GetString("PatientRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatientRequestReceivedForSampling.
        /// </summary>
        public static string PatientRequestReceivedForSampling {
            get {
                return ResourceManager.GetString("PatientRequestReceivedForSampling", resourceCulture);
            }
        }
    }
}
