//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Status {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Status() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DemoMisrInternationalLab.Resources.Status", typeof(Status).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApprovedByQC.
        /// </summary>
        public static string ApprovedByQC {
            get {
                return ResourceManager.GetString("ApprovedByQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptureResult.
        /// </summary>
        public static string CaptureResult {
            get {
                return ResourceManager.GetString("CaptureResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditedByQC.
        /// </summary>
        public static string EditedByQC {
            get {
                return ResourceManager.GetString("EditedByQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotDeliveredByLab.
        /// </summary>
        public static string NotDeliveredByLab {
            get {
                return ResourceManager.GetString("NotDeliveredByLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingForAnalysising.
        /// </summary>
        public static string PendingForAnalysising {
            get {
                return ResourceManager.GetString("PendingForAnalysising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingForReporting.
        /// </summary>
        public static string PendingForReporting {
            get {
                return ResourceManager.GetString("PendingForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingForSampling.
        /// </summary>
        public static string PendingForSampling {
            get {
                return ResourceManager.GetString("PendingForSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        public static string Printed {
            get {
                return ResourceManager.GetString("Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedForAnalysising.
        /// </summary>
        public static string ReceivedForAnalysising {
            get {
                return ResourceManager.GetString("ReceivedForAnalysising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedForReporting.
        /// </summary>
        public static string ReceivedForReporting {
            get {
                return ResourceManager.GetString("ReceivedForReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivedForSampling.
        /// </summary>
        public static string ReceivedForSampling {
            get {
                return ResourceManager.GetString("ReceivedForSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecycledByQC.
        /// </summary>
        public static string RecycledByQC {
            get {
                return ResourceManager.GetString("RecycledByQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RejectedByLab.
        /// </summary>
        public static string RejectedByLab {
            get {
                return ResourceManager.GetString("RejectedByLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedByChemist.
        /// </summary>
        public static string SavedByChemist {
            get {
                return ResourceManager.GetString("SavedByChemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferredByChemist.
        /// </summary>
        public static string TransferredByChemist {
            get {
                return ResourceManager.GetString("TransferredByChemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnderTesting.
        /// </summary>
        public static string UnderTesting {
            get {
                return ResourceManager.GetString("UnderTesting", resourceCulture);
            }
        }
    }
}
