//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.DoctorRefs = new HashSet<DoctorRef>();
            this.LabBranches = new HashSet<LabBranch>();
            this.OrganizationInfoes = new HashSet<OrganizationInfo>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int CityID { get; set; }
        public int ProvinceID { get; set; }
        public string CityName { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual ICollection<DoctorRef> DoctorRefs { get; set; }
        public virtual ICollection<LabBranch> LabBranches { get; set; }
        public virtual ICollection<OrganizationInfo> OrganizationInfoes { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
