//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorRef
    {
        public DoctorRef()
        {
            this.PatientRequests = new HashSet<PatientRequest>();
        }
    
        public int DoctorRefID { get; set; }
        public string DoctorName { get; set; }
        public Nullable<int> SpecialID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public System.DateTime InsertionDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual DoctorSpecialization DoctorSpecialization { get; set; }
        public virtual ICollection<PatientRequest> PatientRequests { get; set; }
    }
}
