//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAction
    {
        public EntityAction()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public int ActionID { get; set; }
        public string ActionName { get; set; }
        public string ActionDescription { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
