//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationConsuming
    {
        public int OrganizationID { get; set; }
        public int AnalysisID { get; set; }
        public Nullable<decimal> ConsumingPercentage { get; set; }
    }
}
