//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.OrganizationConditions = new HashSet<OrganizationCondition>();
            this.OrganizationInfoes = new HashSet<OrganizationInfo>();
            this.PatientRequests = new HashSet<PatientRequest>();
        }
    
        public int OrganizationID { get; set; }
        public string OrganizationName { get; set; }
        public int PackageID { get; set; }
        public System.DateTime InsertionDate { get; set; }
        public int EmployeeID { get; set; }
        public bool PatientCanReceiveResult { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Package Package { get; set; }
        public virtual ICollection<OrganizationCondition> OrganizationConditions { get; set; }
        public virtual ICollection<OrganizationInfo> OrganizationInfoes { get; set; }
        public virtual ICollection<PatientRequest> PatientRequests { get; set; }
    }
}
