//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageCostList
    {
        public int PackageID { get; set; }
        public int AnalysisID { get; set; }
        public decimal CurrentAnalysisDiscountRate { get; set; }
        public Nullable<decimal> NewAnalysisDiscountRate { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual Package Package { get; set; }
    }
}
