//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRequest
    {
        public PatientRequest()
        {
            this.PatientRequestAnalysis = new HashSet<PatientRequestAnalysi>();
            this.PatientRequestPayments = new HashSet<PatientRequestPayment>();
            this.PatientRequestStatus = new HashSet<PatientRequestStatu>();
        }
    
        public int RequestID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int EmployeeID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> DoctorRefID { get; set; }
        public string Priority { get; set; }
        public Nullable<int> OrganizationID { get; set; }
        public string RequestedRefID { get; set; }
        public string AttachmentSession { get; set; }
        public Nullable<decimal> ExtraDiscount { get; set; }
        public Nullable<decimal> ExtraCost { get; set; }
        public Nullable<decimal> TotalPatientCost { get; set; }
        public Nullable<decimal> TotalOrganizationCost { get; set; }
        public int RequestNumber { get; set; }
    
        public virtual DoctorRef DoctorRef { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<PatientRequestAnalysi> PatientRequestAnalysis { get; set; }
        public virtual ICollection<PatientRequestPayment> PatientRequestPayments { get; set; }
        public virtual ICollection<PatientRequestStatu> PatientRequestStatus { get; set; }
    }
}
