//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMisrInternationalLab.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRequestStatu
    {
        public int RequestStatusID { get; set; }
        public int RequestID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime StatusDate { get; set; }
        public int EmployeeID { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PatientRequest PatientRequest { get; set; }
        public virtual Status Status { get; set; }
    }
}
